name: "terraform"

on:
  push:
    branches: [main]
    paths: ["src/**"]
  workflow_dispatch:
jobs:
  terraform:
    name: "terraform aplly"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}
      - name: Checkout
        uses: actions/checkout@v5    

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: terraform init
        working-directory: .
        run: terraform init -backend-config="bucket=${{secrets.AWS_BUCKET_NAME}}" -backend-config="key=${{secrets.AWS_BUCKET_FILE}}" 

      - name: terraform apply
        working-directory: .
        run: terraform apply --auto-aprove
